# Example workflow
name: Format

on:
    push:

jobs:
    formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2 # v2 minimum required

            - name: Setup Java
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '16'

            - name: Setup google-java-format
              run: wget https://github.com/google/google-java-format/releases/download/v1.10.0/google-java-format-1.10.0-all-deps.jar

            - name: Format code
              run: java --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -jar google-java-format-1.10.0-all-deps.jar --set-exit-if-changed -a -r $(find . -type f -name "*.java") && exit 0

            - name: Commit formatted code
              uses: EndBug/add-and-commit@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  add: 'src/'

                  author_name: ${{ github.event.pusher.name }}
                  author_email: ${{ github.event.pusher.email }}

                  message: 'Apply fixes from CI


                  Co-authored-by: github-actions[bot] <action@github.com>'
